version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_insta
    volumes:
      - insta-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env-non-dev
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7
    container_name: redis_insta
    command: --port 5380
    expose:
      - 5380
    env_file:
      - .env-non-dev
    restart: always

  app:
    build:
      context: .
    container_name: app_insta_vpn
    env_file:
      - .env-non-dev
    command: ["/insta_vpn/docker/app.sh"]
    ports:
      - 55713:55713
    depends_on:
      - db
      - redis
    restart: always

  celery:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_insta
    command: ["/insta_vpn/docker/celery.sh", "celery"]
    depends_on:
      - redis
    restart: always

  flower:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: flower_insta
    command: ["/insta_vpn/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8889:5555
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_insta
    depends_on:
      - db
      - redis
    ports:
      - "5050:5050"
    env_file:
      - .env-non-dev
    restart: always

volumes:
  insta-db-data: