"""update profile

Revision ID: 06fff97208e7
Revises: d4e6109a7314
Create Date: 2023-09-06 00:12:47.036992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fff97208e7'
down_revision = 'd4e6109a7314'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('used_bytes', sa.Integer(), nullable=True))
    op.drop_column('profile', 'user_bytes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('user_bytes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('profile', 'used_bytes')
    # ### end Alembic commands ###
