"""if delete serever -> drop keys cascade

Revision ID: 562b7c3a3c6b
Revises: ff3db3fa717c
Create Date: 2023-10-20 13:40:22.911330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "562b7c3a3c6b"
down_revision = "ff3db3fa717c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "static_key_server_id_fkey", "static_key", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "static_key", "server", ["server_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "static_key", type_="foreignkey")
    op.create_foreign_key(
        "static_key_server_id_fkey",
        "static_key",
        "server",
        ["server_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
