"""add on server onupdate=cascade

Revision ID: 9b923fb018dc
Revises: b5db5dcbd7ca
Create Date: 2023-11-15 18:03:44.010607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b923fb018dc"
down_revision = "b5db5dcbd7ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("server_vpn_type_id_fkey", "server", type_="foreignkey")
    op.create_foreign_key(
        None,
        "server",
        "vpn_type",
        ["vpn_type_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "server", type_="foreignkey")
    op.create_foreign_key(
        "server_vpn_type_id_fkey",
        "server",
        "vpn_type",
        ["vpn_type_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
