"""rename outline_key table

Revision ID: d1b8e04e37cb
Revises: 87723f49e166
Create Date: 2023-11-07 01:13:57.689346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1b8e04e37cb"
down_revision = "87723f49e166"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outline_key",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=True),
        sa.Column("key_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(), nullable=True),
        sa.Column("access_url", sa.String(), nullable=True),
        sa.Column("used_bytes", sa.Integer(), nullable=True),
        sa.Column("data_limit", sa.Integer(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["server_id"], ["server.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("server_id", "key_id", name="_key_server_uc"),
    )
    op.create_foreign_key(
        None,
        "profile",
        "outline_key",
        ["shadowsocks_key_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profile", type_="foreignkey")
    op.drop_table("outline_key")
    # ### end Alembic commands ###
