"""add field gift_days in referent

Revision ID: c509e25eb5dd
Revises: c6aeaba5a3b0
Create Date: 2023-11-22 03:02:46.139410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c509e25eb5dd"
down_revision = "c6aeaba5a3b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referent", sa.Column("gift_days", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("referent", "gift_days")
    # ### end Alembic commands ###
