"""in payment table rename sum to amount

Revision ID: fb4374da259c
Revises: 878f29205a59
Create Date: 2023-11-29 19:04:24.633554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fb4374da259c"
down_revision = "878f29205a59"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("amount", sa.Integer(), nullable=True))
    op.drop_column("payment", "sum")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment",
        sa.Column("sum", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("payment", "amount")
    # ### end Alembic commands ###
