"""remove is_active: default=True in server and outline table

Revision ID: 6b7b789640a5
Revises: d1b8e04e37cb
Create Date: 2023-11-07 15:35:51.273008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6b7b789640a5"
down_revision = "d1b8e04e37cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
