"""remove field vless in table Profile

Revision ID: 5a14e6bfdd8c
Revises: 698c74bf0dfd
Create Date: 2023-11-09 14:09:23.914681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5a14e6bfdd8c"
down_revision = "698c74bf0dfd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("profile_vless_key_id_key", "profile", type_="unique")
    op.drop_constraint(
        "profile_vpn_type_id_fkey", "profile", type_="foreignkey"
    )
    op.drop_constraint(
        "profile_vless_key_id_fkey", "profile", type_="foreignkey"
    )
    op.drop_column("profile", "vpn_type_id")
    op.drop_column("profile", "vless_key_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profile",
        sa.Column(
            "vless_key_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "profile",
        sa.Column(
            "vpn_type_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "profile_vless_key_id_fkey",
        "profile",
        "vless_key",
        ["vless_key_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "profile_vpn_type_id_fkey",
        "profile",
        "vpn_type",
        ["vpn_type_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_unique_constraint(
        "profile_vless_key_id_key", "profile", ["vless_key_id"]
    )
    # ### end Alembic commands ###
