"""add budget_amount remove password

Revision ID: cb6572401e26
Revises: 6eb6b72fe2f1
Create Date: 2023-12-26 21:59:36.856751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb6572401e26"
down_revision = "6eb6b72fe2f1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referent", sa.Column("budget_amount", sa.Integer(), nullable=True)
    )
    op.drop_column("referent", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referent",
        sa.Column(
            "password", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("referent", "budget_amount")
    # ### end Alembic commands ###
