"""add unique constraint to referent table

Revision ID: 041491198d9c
Revises: 3b54459bcf01
Create Date: 2023-11-27 04:10:39.683952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "041491198d9c"
down_revision = "3b54459bcf01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_telegram_referent_type_uc",
        "referent",
        ["telegram_id", "referent_type_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "_telegram_referent_type_uc", "referent", type_="unique"
    )
    # ### end Alembic commands ###
