"""remove partner table

Revision ID: 3f446a4736e3
Revises: d0c5a572b232
Create Date: 2023-10-28 12:41:49.425973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f446a4736e3"
down_revision = "d0c5a572b232"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referral", sa.Column("telegram_id", sa.BigInteger(), nullable=True)
    )
    op.drop_column("referral", "partner_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referral",
        sa.Column(
            "partner_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("referral", "telegram_id")
    # ### end Alembic commands ###
