"""update account rename trial_was_used

Revision ID: e9249795677f
Revises: 3f446a4736e3
Create Date: 2023-10-28 13:15:55.361101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e9249795677f"
down_revision = "3f446a4736e3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account", sa.Column("trial_was_used", sa.Boolean(), nullable=True)
    )
    op.drop_column("account", "trial")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account",
        sa.Column("trial", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("account", "trial_was_used")
    # ### end Alembic commands ###
