"""add payment type table

Revision ID: baef9a0bd089
Revises: b5bd9c357598
Create Date: 2023-12-18 18:12:04.874693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "baef9a0bd089"
down_revision = "b5bd9c357598"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment_type")
    # ### end Alembic commands ###
