"""Add referent_type table

Revision ID: 3b54459bcf01
Revises: c509e25eb5dd
Create Date: 2023-11-27 02:32:43.494912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3b54459bcf01"
down_revision = "c509e25eb5dd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referent_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column(
        "referent", sa.Column("referent_type_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "referent",
        "referent_type",
        ["referent_type_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "referent", type_="foreignkey")
    op.drop_column("referent", "referent_type_id")
    op.drop_table("referent_type")
    # ### end Alembic commands ###
