"""remane referral to referent

Revision ID: b059941664f8
Revises: 1402e2c1d585
Create Date: 2023-10-28 18:23:20.671435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b059941664f8"
down_revision = "1402e2c1d585"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referent",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("referral_link", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "account", sa.Column("referent_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "account",
        "referent",
        ["referent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("account", "referral_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account",
        sa.Column(
            "referral_id", sa.UUID(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "account", type_="foreignkey")
    op.drop_column("account", "referent_id")
    op.drop_table("referent")
    # ### end Alembic commands ###
