"""update ralationship server and outline_key

Revision ID: b5db5dcbd7ca
Revises: c7b2b85dcafc
Create Date: 2023-11-14 19:22:53.945600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b5db5dcbd7ca"
down_revision = "c7b2b85dcafc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "outline_key_server_id_fkey", "outline_key", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "outline_key",
        "server",
        ["server_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "outline_key", type_="foreignkey")
    op.create_foreign_key(
        "outline_key_server_id_fkey",
        "outline_key",
        "server",
        ["server_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
