"""add can_pay_out and sbp_number

Revision ID: 26ff36adc00c
Revises: b059941664f8
Create Date: 2023-10-29 21:31:24.115306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "26ff36adc00c"
down_revision = "b059941664f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account", sa.Column("can_pay_out", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "referent", sa.Column("sbp_number", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("referent", "sbp_number")
    op.drop_column("account", "can_pay_out")
    # ### end Alembic commands ###
