"""add column was_paying in Account table

Revision ID: b5bd9c357598
Revises: fb4374da259c
Create Date: 2023-12-13 03:09:45.255091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b5bd9c357598"
down_revision = "fb4374da259c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account", sa.Column("was_paying", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "was_paying")
    # ### end Alembic commands ###
