"""update server model

Revision ID: 87723f49e166
Revises: 932ca11a5514
Create Date: 2023-11-06 23:05:12.550193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87723f49e166"
down_revision = "932ca11a5514"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "server", sa.Column("marzban_login", sa.String(), nullable=True)
    )
    op.add_column(
        "server", sa.Column("marzban_pass", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("server", "marzban_pass")
    op.drop_column("server", "marzban_login")
    # ### end Alembic commands ###
