"""foreign key static_key_id unique

Revision ID: 94e43adf11cc
Revises: 562b7c3a3c6b
Create Date: 2023-10-20 16:15:23.402343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "94e43adf11cc"
down_revision = "562b7c3a3c6b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "profile", ["static_key_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profile", type_="unique")
    # ### end Alembic commands ###
