"""update ip_address

Revision ID: 39e30afd397f
Revises: 867e434a20c2
Create Date: 2023-07-27 15:26:37.851558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e30afd397f'
down_revision = '867e434a20c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ips_addresses', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'ips_addresses', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ips_addresses', type_='unique')
    op.drop_column('ips_addresses', 'is_active')
    # ### end Alembic commands ###
