"""tariff period_days

Revision ID: 3ea67fd8f74d
Revises: 6be104d3d904
Create Date: 2023-09-17 16:47:18.564017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea67fd8f74d'
down_revision = '6be104d3d904'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff', sa.Column('period_days', sa.Integer(), nullable=True))
    op.drop_column('tariff', 'period_unix')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff', sa.Column('period_unix', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tariff', 'period_days')
    # ### end Alembic commands ###
