"""update account

Revision ID: 4bf623a9f7c4
Revises: dd9da74445b0
Create Date: 2023-07-27 23:16:48.673513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf623a9f7c4'
down_revision = 'dd9da74445b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['telegram_id'])
    op.create_unique_constraint(None, 'account', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
