"""update ip_address

Revision ID: 5b8c817b5db1
Revises: f175ecec18a9
Create Date: 2023-08-05 19:00:58.833188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8c817b5db1'
down_revision = 'f175ecec18a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ips_addresses', sa.Column('port', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ips_addresses', 'port')
    # ### end Alembic commands ###
