"""update account

Revision ID: 88368cada1d3
Revises: 06fff97208e7
Create Date: 2023-09-06 14:28:11.622455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88368cada1d3'
down_revision = '06fff97208e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_telegram_id_key', 'account', type_='unique')
    op.drop_column('account', 'telegram_id')
    op.drop_column('account', 'time_zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('time_zone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('telegram_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint('account_telegram_id_key', 'account', ['telegram_id'])
    # ### end Alembic commands ###
