"""update server

Revision ID: 935fb05384e9
Revises: 38dd37a47fb0
Create Date: 2023-09-05 20:22:46.165788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935fb05384e9'
down_revision = '38dd37a47fb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('fact_client', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'fact_client')
    # ### end Alembic commands ###
