"""initial

Revision ID: c1db3f9cf628
Revises: 6500e7dec34f
Create Date: 2023-07-28 07:23:18.134516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1db3f9cf628'
down_revision = '6500e7dec34f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff', sa.Column('period_unix', sa.Integer(), nullable=True))
    op.drop_column('tariff', 'period_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff', sa.Column('period_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tariff', 'period_unix')
    # ### end Alembic commands ###
