"""update server 2

Revision ID: d4e6109a7314
Revises: 935fb05384e9
Create Date: 2023-09-05 20:28:51.403011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e6109a7314'
down_revision = '935fb05384e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'is_active')
    # ### end Alembic commands ###
