"""update profile 3

Revision ID: d7559911768a
Revises: 434eef8234dc
Create Date: 2023-09-06 14:57:20.064767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7559911768a'
down_revision = '434eef8234dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_account_server_access_url_uc', 'profile', type_='unique')
    op.create_unique_constraint('_server_access_url_uc', 'profile', ['server_id', 'access_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_server_access_url_uc', 'profile', type_='unique')
    op.create_unique_constraint('_account_server_access_url_uc', 'profile', ['account_id', 'server_id', 'access_url'])
    # ### end Alembic commands ###
