"""update ip_addresses

Revision ID: d7e1e8bfa955
Revises: 5b8c817b5db1
Create Date: 2023-08-05 21:41:45.494797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e1e8bfa955'
down_revision = '5b8c817b5db1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ips_addresses', sa.Column('max_client', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ips_addresses', 'max_client')
    # ### end Alembic commands ###
