"""update tariff

Revision ID: dd9da74445b0
Revises: 39e30afd397f
Create Date: 2023-07-27 18:13:02.928213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9da74445b0'
down_revision = '39e30afd397f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariff', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'tariff', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tariff', type_='unique')
    op.drop_column('tariff', 'is_active')
    # ### end Alembic commands ###
