"""add users

Revision ID: ee2cb23bf988
Revises: 3ea67fd8f74d
Create Date: 2023-09-17 17:33:34.383441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2cb23bf988'
down_revision = '3ea67fd8f74d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
