"""uique constraint for profile

Revision ID: f175ecec18a9
Revises: c1db3f9cf628
Create Date: 2023-07-28 16:01:41.769389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f175ecec18a9'
down_revision = 'c1db3f9cf628'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_account_ip_address_peer_name_uc', 'profile', ['account_id', 'ip_address_id', 'peer_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_account_ip_address_peer_name_uc', 'profile', type_='unique')
    # ### end Alembic commands ###
